/* This file was generated by SableCC (http://www.sablecc.org/). */

package cida.node;

import cida.analysis.*;

@SuppressWarnings("nls")
public final class TAnswerT extends Token
{
    public TAnswerT()
    {
        super.setText("answer");
    }

    public TAnswerT(int line, int pos)
    {
        super.setText("answer");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TAnswerT(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTAnswerT(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TAnswerT text.");
    }
}
