/* This file was generated by SableCC (http://www.sablecc.org/). */

package cida.node;

import cida.analysis.*;

@SuppressWarnings("nls")
public final class TAuxBlocExprBloc extends Token
{
    public TAuxBlocExprBloc(String text)
    {
        setText(text);
    }

    public TAuxBlocExprBloc(String text, int line, int pos)
    {
        setText(text);
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TAuxBlocExprBloc(getText(), getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTAuxBlocExprBloc(this);
    }
}
