/* This file was generated by SableCC (http://www.sablecc.org/). */

package cida.node;

import cida.analysis.*;

@SuppressWarnings("nls")
public final class TAuxOtherwiseDecCasam extends Token
{
    public TAuxOtherwiseDecCasam(String text)
    {
        setText(text);
    }

    public TAuxOtherwiseDecCasam(String text, int line, int pos)
    {
        setText(text);
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TAuxOtherwiseDecCasam(getText(), getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTAuxOtherwiseDecCasam(this);
    }
}
