/* This file was generated by SableCC (http://www.sablecc.org/). */

package cida.node;

import cida.analysis.*;

@SuppressWarnings("nls")
public final class TAuxRecbeExpr extends Token
{
    public TAuxRecbeExpr(String text)
    {
        setText(text);
    }

    public TAuxRecbeExpr(String text, int line, int pos)
    {
        setText(text);
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TAuxRecbeExpr(getText(), getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTAuxRecbeExpr(this);
    }
}
