/* This file was generated by SableCC (http://www.sablecc.org/). */

package cida.node;

import cida.analysis.*;

@SuppressWarnings("nls")
public final class TFalse extends Token
{
    public TFalse()
    {
        super.setText("no");
    }

    public TFalse(int line, int pos)
    {
        super.setText("no");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TFalse(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTFalse(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TFalse text.");
    }
}
