/* This file was generated by SableCC (http://www.sablecc.org/). */

package cida.node;

import cida.analysis.*;

@SuppressWarnings("nls")
public final class TNumberT extends Token
{
    public TNumberT()
    {
        super.setText("number");
    }

    public TNumberT(int line, int pos)
    {
        super.setText("number");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TNumberT(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTNumberT(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TNumberT text.");
    }
}
