/* This file was generated by SableCC (http://www.sablecc.org/). */

package cida.node;

import cida.analysis.*;

@SuppressWarnings("nls")
public final class TSymbolT extends Token
{
    public TSymbolT()
    {
        super.setText("symbol");
    }

    public TSymbolT(int line, int pos)
    {
        super.setText("symbol");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TSymbolT(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTSymbolT(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TSymbolT text.");
    }
}
