/* This file was generated by SableCC (http://www.sablecc.org/). */

package cida.node;

import cida.analysis.*;

@SuppressWarnings("nls")
public final class TVectorT extends Token
{
    public TVectorT()
    {
        super.setText("vector");
    }

    public TVectorT(int line, int pos)
    {
        super.setText("vector");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TVectorT(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTVectorT(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TVectorT text.");
    }
}
